# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pubsub_sys_pb2 as pubsub__sys__pb2


class RegistryServiceStub(object):
    """----------------------------------- RegistryServer -------------------------------- //
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterServer = channel.unary_unary(
                '/pubsub_system.RegistryService/RegisterServer',
                request_serializer=pubsub__sys__pb2.RegisterServerRequest.SerializeToString,
                response_deserializer=pubsub__sys__pb2.RegisterServerResponse.FromString,
                )
        self.GetServerList = channel.unary_unary(
                '/pubsub_system.RegistryService/GetServerList',
                request_serializer=pubsub__sys__pb2.GetServerListRequest.SerializeToString,
                response_deserializer=pubsub__sys__pb2.GetServerListResponse.FromString,
                )


class RegistryServiceServicer(object):
    """----------------------------------- RegistryServer -------------------------------- //
    """

    def RegisterServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterServer,
                    request_deserializer=pubsub__sys__pb2.RegisterServerRequest.FromString,
                    response_serializer=pubsub__sys__pb2.RegisterServerResponse.SerializeToString,
            ),
            'GetServerList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerList,
                    request_deserializer=pubsub__sys__pb2.GetServerListRequest.FromString,
                    response_serializer=pubsub__sys__pb2.GetServerListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pubsub_system.RegistryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegistryService(object):
    """----------------------------------- RegistryServer -------------------------------- //
    """

    @staticmethod
    def RegisterServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pubsub_system.RegistryService/RegisterServer',
            pubsub__sys__pb2.RegisterServerRequest.SerializeToString,
            pubsub__sys__pb2.RegisterServerResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetServerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pubsub_system.RegistryService/GetServerList',
            pubsub__sys__pb2.GetServerListRequest.SerializeToString,
            pubsub__sys__pb2.GetServerListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ServerServiceStub(object):
    """----------------------------------- Server -------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.JoinServer = channel.unary_unary(
                '/pubsub_system.ServerService/JoinServer',
                request_serializer=pubsub__sys__pb2.ServerJoinRequest.SerializeToString,
                response_deserializer=pubsub__sys__pb2.ServerJoinResponse.FromString,
                )
        self.LeaveServer = channel.unary_unary(
                '/pubsub_system.ServerService/LeaveServer',
                request_serializer=pubsub__sys__pb2.ServerLeaveRequest.SerializeToString,
                response_deserializer=pubsub__sys__pb2.ServerLeaveResponse.FromString,
                )
        self.GetArticles = channel.unary_unary(
                '/pubsub_system.ServerService/GetArticles',
                request_serializer=pubsub__sys__pb2.GetArticlesRequest.SerializeToString,
                response_deserializer=pubsub__sys__pb2.GetArticlesResponse.FromString,
                )
        self.PublishArticle = channel.unary_unary(
                '/pubsub_system.ServerService/PublishArticle',
                request_serializer=pubsub__sys__pb2.PublishArticleRequest.SerializeToString,
                response_deserializer=pubsub__sys__pb2.PublishArticleResponse.FromString,
                )


class ServerServiceServicer(object):
    """----------------------------------- Server -------------------------------- //

    """

    def JoinServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArticles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishArticle(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'JoinServer': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinServer,
                    request_deserializer=pubsub__sys__pb2.ServerJoinRequest.FromString,
                    response_serializer=pubsub__sys__pb2.ServerJoinResponse.SerializeToString,
            ),
            'LeaveServer': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveServer,
                    request_deserializer=pubsub__sys__pb2.ServerLeaveRequest.FromString,
                    response_serializer=pubsub__sys__pb2.ServerLeaveResponse.SerializeToString,
            ),
            'GetArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArticles,
                    request_deserializer=pubsub__sys__pb2.GetArticlesRequest.FromString,
                    response_serializer=pubsub__sys__pb2.GetArticlesResponse.SerializeToString,
            ),
            'PublishArticle': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishArticle,
                    request_deserializer=pubsub__sys__pb2.PublishArticleRequest.FromString,
                    response_serializer=pubsub__sys__pb2.PublishArticleResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pubsub_system.ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """----------------------------------- Server -------------------------------- //

    """

    @staticmethod
    def JoinServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pubsub_system.ServerService/JoinServer',
            pubsub__sys__pb2.ServerJoinRequest.SerializeToString,
            pubsub__sys__pb2.ServerJoinResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pubsub_system.ServerService/LeaveServer',
            pubsub__sys__pb2.ServerLeaveRequest.SerializeToString,
            pubsub__sys__pb2.ServerLeaveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pubsub_system.ServerService/GetArticles',
            pubsub__sys__pb2.GetArticlesRequest.SerializeToString,
            pubsub__sys__pb2.GetArticlesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def PublishArticle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/pubsub_system.ServerService/PublishArticle',
            pubsub__sys__pb2.PublishArticleRequest.SerializeToString,
            pubsub__sys__pb2.PublishArticleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
