# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: worker_register.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15worker_register.proto\x12\x1aworker_registration_system\"!\n\x0fGeneralResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\"-\n\x16GeneralMessageResponse\x12\x13\n\x0bmessage_val\x18\x01 \x01(\t\"%\n\x0eGeneralRequest\x12\x13\n\x0bmessage_val\x18\x01 \x01(\t\",\n\x10\x41\x64\x64MapperRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"-\n\x11\x41\x64\x64ReducerRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t2\xe5\x01\n\rMasterService\x12h\n\taddMapper\x12,.worker_registration_system.AddMapperRequest\x1a+.worker_registration_system.GeneralResponse\"\x00\x12j\n\naddReducer\x12-.worker_registration_system.AddReducerRequest\x1a+.worker_registration_system.GeneralResponse\"\x00\x32\x85\x01\n\rMapperService\x12t\n\x10startComputation\x12*.worker_registration_system.GeneralRequest\x1a\x32.worker_registration_system.GeneralMessageResponse\"\x00\x32\x86\x01\n\x0eReducerService\x12t\n\x10startComputation\x12*.worker_registration_system.GeneralRequest\x1a\x32.worker_registration_system.GeneralMessageResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_register_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENERALRESPONSE._serialized_start=53
  _GENERALRESPONSE._serialized_end=86
  _GENERALMESSAGERESPONSE._serialized_start=88
  _GENERALMESSAGERESPONSE._serialized_end=133
  _GENERALREQUEST._serialized_start=135
  _GENERALREQUEST._serialized_end=172
  _ADDMAPPERREQUEST._serialized_start=174
  _ADDMAPPERREQUEST._serialized_end=218
  _ADDREDUCERREQUEST._serialized_start=220
  _ADDREDUCERREQUEST._serialized_end=265
  _MASTERSERVICE._serialized_start=268
  _MASTERSERVICE._serialized_end=497
  _MAPPERSERVICE._serialized_start=500
  _MAPPERSERVICE._serialized_end=633
  _REDUCERSERVICE._serialized_start=636
  _REDUCERSERVICE._serialized_end=770
# @@protoc_insertion_point(module_scope)
