# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: readwrite_sys.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13readwrite_sys.proto\x12\x10readwrite_system\x1a\x1fgoogle/protobuf/timestamp.proto\"\x07\n\x05\x45mpty\"&\n\x0fGeneralResponse\x12\x13\n\x0bmessage_val\x18\x01 \x01(\t\",\n\x10\x41\x64\x64ServerRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\";\n\x0cWriteRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\x12\x0c\n\x04uuid\x18\x03 \x01(\t\"Z\n\rWriteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04uuid\x18\x02 \x01(\t\x12+\n\x07version\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1b\n\x0bReadRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\"j\n\x0cReadResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\x12+\n\x07version\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1d\n\rDeleteRequest\x12\x0c\n\x04uuid\x18\x01 \x01(\t\" \n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2\xf3\x01\n\rServerService\x12J\n\x05write\x12\x1e.readwrite_system.WriteRequest\x1a\x1f.readwrite_system.WriteResponse\"\x00\x12G\n\x04read\x12\x1d.readwrite_system.ReadRequest\x1a\x1e.readwrite_system.ReadResponse\"\x00\x12M\n\x06\x64\x65lete\x12\x1f.readwrite_system.DeleteRequest\x1a .readwrite_system.DeleteResponse\"\x00\x32\xe3\x02\n\x15RegistryServerService\x12T\n\taddServer\x12\".readwrite_system.AddServerRequest\x1a!.readwrite_system.GeneralResponse\"\x00\x12O\n\rgetServerList\x12\x17.readwrite_system.Empty\x1a!.readwrite_system.GeneralResponse\"\x00\x30\x01\x12P\n\x0egetReadServers\x12\x17.readwrite_system.Empty\x1a!.readwrite_system.GeneralResponse\"\x00\x30\x01\x12Q\n\x0fgetWriteServers\x12\x17.readwrite_system.Empty\x1a!.readwrite_system.GeneralResponse\"\x00\x30\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'readwrite_sys_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=74
  _EMPTY._serialized_end=81
  _GENERALRESPONSE._serialized_start=83
  _GENERALRESPONSE._serialized_end=121
  _ADDSERVERREQUEST._serialized_start=123
  _ADDSERVERREQUEST._serialized_end=167
  _WRITEREQUEST._serialized_start=169
  _WRITEREQUEST._serialized_end=228
  _WRITERESPONSE._serialized_start=230
  _WRITERESPONSE._serialized_end=320
  _READREQUEST._serialized_start=322
  _READREQUEST._serialized_end=349
  _READRESPONSE._serialized_start=351
  _READRESPONSE._serialized_end=457
  _DELETEREQUEST._serialized_start=459
  _DELETEREQUEST._serialized_end=488
  _DELETERESPONSE._serialized_start=490
  _DELETERESPONSE._serialized_end=522
  _SERVERSERVICE._serialized_start=525
  _SERVERSERVICE._serialized_end=768
  _REGISTRYSERVERSERVICE._serialized_start=771
  _REGISTRYSERVERSERVICE._serialized_end=1126
# @@protoc_insertion_point(module_scope)
