# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import readwrite_sys_pb2 as readwrite__sys__pb2


class ServerServiceStub(object):
    """----------------------------------- Server -------------------------------- //

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.write = channel.unary_unary(
                '/readwrite_system.ServerService/write',
                request_serializer=readwrite__sys__pb2.WriteRequest.SerializeToString,
                response_deserializer=readwrite__sys__pb2.WriteResponse.FromString,
                )
        self.read = channel.unary_unary(
                '/readwrite_system.ServerService/read',
                request_serializer=readwrite__sys__pb2.ReadRequest.SerializeToString,
                response_deserializer=readwrite__sys__pb2.ReadResponse.FromString,
                )
        self.delete = channel.unary_unary(
                '/readwrite_system.ServerService/delete',
                request_serializer=readwrite__sys__pb2.DeleteRequest.SerializeToString,
                response_deserializer=readwrite__sys__pb2.DeleteResponse.FromString,
                )


class ServerServiceServicer(object):
    """----------------------------------- Server -------------------------------- //

    """

    def write(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def read(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def delete(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'write': grpc.unary_unary_rpc_method_handler(
                    servicer.write,
                    request_deserializer=readwrite__sys__pb2.WriteRequest.FromString,
                    response_serializer=readwrite__sys__pb2.WriteResponse.SerializeToString,
            ),
            'read': grpc.unary_unary_rpc_method_handler(
                    servicer.read,
                    request_deserializer=readwrite__sys__pb2.ReadRequest.FromString,
                    response_serializer=readwrite__sys__pb2.ReadResponse.SerializeToString,
            ),
            'delete': grpc.unary_unary_rpc_method_handler(
                    servicer.delete,
                    request_deserializer=readwrite__sys__pb2.DeleteRequest.FromString,
                    response_serializer=readwrite__sys__pb2.DeleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'readwrite_system.ServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ServerService(object):
    """----------------------------------- Server -------------------------------- //

    """

    @staticmethod
    def write(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/readwrite_system.ServerService/write',
            readwrite__sys__pb2.WriteRequest.SerializeToString,
            readwrite__sys__pb2.WriteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def read(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/readwrite_system.ServerService/read',
            readwrite__sys__pb2.ReadRequest.SerializeToString,
            readwrite__sys__pb2.ReadResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def delete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/readwrite_system.ServerService/delete',
            readwrite__sys__pb2.DeleteRequest.SerializeToString,
            readwrite__sys__pb2.DeleteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class RegistryServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.addServer = channel.unary_unary(
                '/readwrite_system.RegistryServerService/addServer',
                request_serializer=readwrite__sys__pb2.AddServerRequest.SerializeToString,
                response_deserializer=readwrite__sys__pb2.GeneralResponse.FromString,
                )
        self.getServerList = channel.unary_stream(
                '/readwrite_system.RegistryServerService/getServerList',
                request_serializer=readwrite__sys__pb2.Empty.SerializeToString,
                response_deserializer=readwrite__sys__pb2.GeneralResponse.FromString,
                )
        self.getReadServers = channel.unary_stream(
                '/readwrite_system.RegistryServerService/getReadServers',
                request_serializer=readwrite__sys__pb2.Empty.SerializeToString,
                response_deserializer=readwrite__sys__pb2.GeneralResponse.FromString,
                )
        self.getWriteServers = channel.unary_stream(
                '/readwrite_system.RegistryServerService/getWriteServers',
                request_serializer=readwrite__sys__pb2.Empty.SerializeToString,
                response_deserializer=readwrite__sys__pb2.GeneralResponse.FromString,
                )


class RegistryServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def addServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getServerList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getReadServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getWriteServers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistryServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'addServer': grpc.unary_unary_rpc_method_handler(
                    servicer.addServer,
                    request_deserializer=readwrite__sys__pb2.AddServerRequest.FromString,
                    response_serializer=readwrite__sys__pb2.GeneralResponse.SerializeToString,
            ),
            'getServerList': grpc.unary_stream_rpc_method_handler(
                    servicer.getServerList,
                    request_deserializer=readwrite__sys__pb2.Empty.FromString,
                    response_serializer=readwrite__sys__pb2.GeneralResponse.SerializeToString,
            ),
            'getReadServers': grpc.unary_stream_rpc_method_handler(
                    servicer.getReadServers,
                    request_deserializer=readwrite__sys__pb2.Empty.FromString,
                    response_serializer=readwrite__sys__pb2.GeneralResponse.SerializeToString,
            ),
            'getWriteServers': grpc.unary_stream_rpc_method_handler(
                    servicer.getWriteServers,
                    request_deserializer=readwrite__sys__pb2.Empty.FromString,
                    response_serializer=readwrite__sys__pb2.GeneralResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'readwrite_system.RegistryServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RegistryServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def addServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/readwrite_system.RegistryServerService/addServer',
            readwrite__sys__pb2.AddServerRequest.SerializeToString,
            readwrite__sys__pb2.GeneralResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getServerList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/readwrite_system.RegistryServerService/getServerList',
            readwrite__sys__pb2.Empty.SerializeToString,
            readwrite__sys__pb2.GeneralResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getReadServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/readwrite_system.RegistryServerService/getReadServers',
            readwrite__sys__pb2.Empty.SerializeToString,
            readwrite__sys__pb2.GeneralResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getWriteServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/readwrite_system.RegistryServerService/getWriteServers',
            readwrite__sys__pb2.Empty.SerializeToString,
            readwrite__sys__pb2.GeneralResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
